spring.application.name=clima-api

server.port=8080

# API externa - Open-Meteo
clima.api.url=https://api.open-meteo.com/v1/forecast

# Localização - Belo Horizonte/MG
clima.api.latitude=-19.9167
clima.api.longitude=-43.9345

# Fuso horário
clima.api.timezone=America/Sao_Paulo